DONE_LIST = r'done_list.txt'
ADB_PATH = r"adb"
IGNORE_DONE_LIST = False
LOGS_DIR = "logcat"
CRASHES_CSV = "crashes.csv"
WAIT_ACTIVITY = 3 # seconds
MONKEY_THROTTLE = 500 # milliseconds
MONKEY_SEED = 100
MONKEY_EVENTS = 500
OUTPUT_DIR = "run-output"
